import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from '../components/Nav';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Associazione ticinese di lotta svizzera',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="autumn">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
